id: ID588DDD1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:11:04+00:00'
last_modified: '2022-06-08T05:19:10.050580+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN53
  title: སྔ་འགྱུར་བཀའ་མའི་ཡིག་རྙིང་ཕྱོགས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    59CA:
      image_group_id: I3CN60
      title: Volume 1 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 903
      order: 1
      base_file: 59CA.txt
    B4E4:
      image_group_id: I3CN61
      title: Volume 2 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 574
      order: 2
      base_file: B4E4.txt
    CCA2:
      image_group_id: I3CN62
      title: Volume 3 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 834
      order: 3
      base_file: CCA2.txt
    '3142':
      image_group_id: I3CN63
      title: Volume 4 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 705
      order: 4
      base_file: 3142.txt
    E9F8:
      image_group_id: I3CN64
      title: Volume 5 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 732
      order: 5
      base_file: E9F8.txt
    9A8E:
      image_group_id: I3CN65
      title: Volume 6 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 328
      order: 6
      base_file: 9A8E.txt
    C082:
      image_group_id: I3CN66
      title: Volume 7 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 293
      order: 7
      base_file: C082.txt
    105B:
      image_group_id: I3CN67
      title: Volume 8 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 579
      order: 8
      base_file: 105B.txt
    744D:
      image_group_id: I3CN68
      title: Volume 9 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 729
      order: 9
      base_file: 744D.txt
    6D8D:
      image_group_id: I3CN69
      title: Volume 10 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 484
      order: 10
      base_file: 6D8D.txt
    80E5:
      image_group_id: I3CN70
      title: Volume 11 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 820
      order: 11
      base_file: 80E5.txt
    3CAA:
      image_group_id: I3CN71
      title: Volume 12 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 611
      order: 12
      base_file: 3CAA.txt
    432B:
      image_group_id: I3CN72
      title: Volume 13 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 427
      order: 13
      base_file: 432B.txt
    301A:
      image_group_id: I3CN73
      title: Volume 14 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 424
      order: 14
      base_file: 301A.txt
    E486:
      image_group_id: I3CN74
      title: Volume 15 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 889
      order: 15
      base_file: E486.txt
    4BAE:
      image_group_id: I3CN75
      title: Volume 16 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 576
      order: 16
      base_file: 4BAE.txt
    3ACC:
      image_group_id: I3CN76
      title: Volume 17 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 276
      order: 17
      base_file: 3ACC.txt
    '6165':
      image_group_id: I3CN77
      title: Volume 18 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 252
      order: 18
      base_file: 6165.txt
    18BA:
      image_group_id: I3CN78
      title: Volume 19 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 843
      order: 19
      base_file: 18BA.txt
    67CC:
      image_group_id: I3CN79
      title: Volume 20 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 304
      order: 20
      base_file: 67CC.txt
    99C0:
      image_group_id: I3CN80
      title: Volume 21 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 608
      order: 21
      base_file: 99C0.txt
    A496:
      image_group_id: I3CN81
      title: Volume 22 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 453
      order: 22
      base_file: A496.txt
    534F:
      image_group_id: I3CN82
      title: Volume 23 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 523
      order: 23
      base_file: 534F.txt
    440F:
      image_group_id: I3CN83
      title: Volume 24 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 700
      order: 24
      base_file: 440F.txt
    FDFD:
      image_group_id: I3CN84
      title: Volume 25 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 474
      order: 25
      base_file: FDFD.txt
    248A:
      image_group_id: I3CN85
      title: Volume 26 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 541
      order: 26
      base_file: 248A.txt
    B3E8:
      image_group_id: I3CN86
      title: Volume 27 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 574
      order: 27
      base_file: B3E8.txt
    B812:
      image_group_id: I3CN87
      title: Volume 28 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 750
      order: 28
      base_file: B812.txt
    9B39:
      image_group_id: I3CN88
      title: Volume 29 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 503
      order: 29
      base_file: 9B39.txt
    0481:
      image_group_id: I3CN89
      title: Volume 30 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 667
      order: 30
      base_file: 0481.txt
    8B44:
      image_group_id: I3CN90
      title: Volume 31 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 338
      order: 31
      base_file: 8B44.txt
    DEEE:
      image_group_id: I3CN91
      title: Volume 32 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 418
      order: 32
      base_file: DEEE.txt
    FA78:
      image_group_id: I3CN92
      title: Volume 33 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 511
      order: 33
      base_file: FA78.txt
    E6A7:
      image_group_id: I3CN93
      title: Volume 34 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 92
      order: 34
      base_file: E6A7.txt
    F44C:
      image_group_id: I3CN94
      title: Volume 35 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 817
      order: 35
      base_file: F44C.txt
    924D:
      image_group_id: I3CN95
      title: Volume 36 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 586
      order: 36
      base_file: 924D.txt
    '9973':
      image_group_id: I3CN96
      title: Volume 37 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 338
      order: 37
      base_file: 9973.txt
    BB44:
      image_group_id: I3CN97
      title: Volume 38 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 484
      order: 38
      base_file: BB44.txt
    CC8E:
      image_group_id: I3CN98
      title: Volume 39 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 588
      order: 39
      base_file: CC8E.txt
    CBCC:
      image_group_id: I3CN99
      title: Volume 40 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 196
      order: 40
      base_file: CBCC.txt
    '7736':
      image_group_id: I3CN100
      title: Volume 41 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 642
      order: 41
      base_file: 7736.txt
    8DB2:
      image_group_id: I3CN101
      title: Volume 42 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 411
      order: 42
      base_file: 8DB2.txt
    0D38:
      image_group_id: I3CN102
      title: Volume 43 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 434
      order: 43
      base_file: 0D38.txt
    4EF9:
      image_group_id: I3CN103
      title: Volume 44 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 566
      order: 44
      base_file: 4EF9.txt
    8F73:
      image_group_id: I3CN104
      title: Volume 45 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 460
      order: 45
      base_file: 8F73.txt
    A99F:
      image_group_id: I3CN105
      title: Volume 46 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 696
      order: 46
      base_file: A99F.txt
    72DB:
      image_group_id: I3CN106
      title: Volume 47 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 1423
      order: 47
      base_file: 72DB.txt
    F619:
      image_group_id: I3CN107
      title: Volume 48 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 1140
      order: 48
      base_file: F619.txt
    '9110':
      image_group_id: I3CN108
      title: Volume 49 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 560
      order: 49
      base_file: 9110.txt
    '6521':
      image_group_id: I3CN109
      title: Volume 50 of snga 'gyur bka' ma'i yig rnying phyogs bsdus/
      total_pages: 404
      order: 50
      base_file: 6521.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
